website:
  layout: layout.html.erb
  pages:
    - speakers
    - schedule
    - information
  no-banner:
    - information
  welcome: speakers # will become index.html
  register_url: https://registrano.com/events/rubyconf-taiwan-2011/registrations/new

lang:
  zh: Chinese
  en: English

sponsors:
  - abbr: rulingcom
    name: Rulingcom
    url: http://www.rulingcom.com/
  - abbr: handlino
    name: Handlino
    url: http://handlino.com/
  - abbr: optimisdev
    name: OptimisDev
    url: http://jobs.ruby.tw/jobs/9-rails-developer-optimiscorp
  - abbr: ossf
    name: OpenFoundry
    url: http://www.openfoundry.org/
  - abbr: verywed
    name: veryWed
    url: http://verywed.com/vwblog/veryWedHR/article/38334