website:
  layout: layout.html.erb
  pages:
    - speakers
    - schedule
    - information
  welcome: speakers # will become index.html

lang:
  zh: Chinese
  en: English

sponsors:
  - abbr: rulingcom
    name: Rulingcom
    url: http://www.rulingcom.com/
  - abbr: Handlino
    name: Handlino
    url: http://www.handlino.com/
  - abbr: optimisdev
    name: OptimisDev
    url: http://optimispt.com/
  - abbr: ossf
    name: OpenFoundry
    url: http://www.openfoundry.org/
